kind: Service
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "360"
  name: marriott-demo-service
  namespace: marriott-demo-migration
spec:
  selector:
    app.kubernetes.io/instance: marriott-demo-migration-marriott-demo-instance
  ports:
    - name: marriott-demo-8001
      protocol: TCP
      port: 8001
      targetPort: 8001
